# Введение в библиотеку NumPy

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


## Создание массивов из списков языка Python

In [6]:
np.array([1, 4, 2, 5, 3]) # Массив целочисленных значений

array([1, 4, 2, 5, 3])

In [8]:
np.array([3.14, 4, 2, 3]) # Массив ограничивается только одним типом. Если добавить float, то он исправит все значения на float

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
np.array([1, 2, 3, 4], dtype='float32') # если нужно явно указать тип данных для массива

array([1., 2., 3., 4.], dtype=float32)

In [10]:
# Вложенные списки прообразуются в многомерный массив
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Создание массивов с нуля

In [19]:
# Создать массив целых чисел длины 10, заполненных нулями
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Массив 3x5 с единицами с плавающей точкой
np.ones((3, 5), dtype='float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [24]:
# Массив, заполненный конкретным значением
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [28]:
# Массив, заданной линейной последовательностью с 0 до 20 с шагом в 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# Массив из пяти значений, равномерно распределенных между 0 и 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# Массив 3x3 равномерно распределенных СЛУЧАЙНЫХ значений между 0  и 1
np.random.random((3, 3))

array([[0.90564238, 0.43472441, 0.23978443],
       [0.50236998, 0.98417084, 0.5123305 ],
       [0.0743034 , 0.16268584, 0.183389  ]])

In [35]:
# Массив 3x3 нормально распределныых случайных значений с медианой 0 и стандартным отклонение 1

# Медиана 0: Медиана — это значение, которое делит распределение на две равные части.
# Если медиана равна 0, это означает, что половина значений меньше или равна 0, а другая половина больше или равна 0.

# Стандартное отклонение 1: Стандартное отклонение — это мера разброса значений относительно средней.
# Если стандартное отклонение равно 1, это указывает на то, что значения распределены относительно среднего значения (в данном случае 0)
# с характерным разбросом, который соответствует нормальному распределению.

np.random.normal(0, 1, (3, 3)) # Или подругому с явными указаниями:  np.random.normal(loc=0, scale=1, size=(3, 3))

array([[-1.23960236, -0.49453963, -1.73737272],
       [ 0.22362313,  0.6696425 , -0.44140676],
       [ 2.26212383,  1.47829973, -0.03397979]])

In [36]:
# Массив 3x3  случайных целых чисел в [0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 6, 2],
       [5, 6, 0],
       [1, 5, 9]])

In [37]:
# Единичная матрица 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
# Неинициализированный мастив из трёх целочисленных значений
# Значения будут производные, случайно оказавшиеся в соответствующих ячейках памяти
np.empty(3)

array([1., 1., 1.])

## Введение в массивы библиотеки NumPy

### Атрибуты массивов библиотеки NumPy

In [39]:
np.random.seed(0) # seed нужен для генерации одних и тех же рандомных значений после каждом выполнении кода

In [41]:
x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [43]:
x3

array([[[3, 7, 0, 1, 9],
        [9, 0, 4, 7, 3],
        [2, 7, 2, 0, 0],
        [4, 5, 5, 6, 8]],

       [[4, 1, 4, 9, 8],
        [1, 1, 7, 9, 9],
        [3, 6, 7, 2, 0],
        [3, 5, 9, 4, 4]],

       [[6, 4, 4, 3, 4],
        [4, 8, 4, 3, 7],
        [5, 5, 0, 1, 5],
        [9, 3, 0, 5, 0]]])

In [42]:
print('x3 ndim:', x3.ndim) # размерность
print('x3 shape:', x3.shape) # размер каждого измерения
print('x3 size:', x3.size) # общий размер массива

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [44]:
print('dtype:', x3.dtype)

dtype: int32


In [46]:
print('itemsize:', x3.itemsize, 'bytes') # размер каждого элемента в байтах
print('nbytes:', x3.nbytes, 'bytes') # полный размер массива в байтах (.itemsize * .size)

itemsize: 4 bytes
nbytes: 240 bytes
